name: deploy
on:
  push:
    branches: ['master']
    
jobs:
  deploy:
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v4

#      - name: Use Node.js
#        uses: actions/setup-node@v4
#        with:
#          node-version: '20.x'
      
      - name: execute
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DIDDEN_SSH_HOST }}
          username: ${{ secrets.DIDDEN_SSH_USERNAME }}
          key: ${{ secrets.DIDDEN_SSH_KEY }}
          port: ${{ secrets.DIDDEN_SSH_PORT }}
          run: |
            cd /
            ls -al
          
      
      #- run: npm ci
      #- run: npm run build --if-present &
